### ISSUE TITLE
Changing the config.yml file overrides the invalid

### ISSUE THREAD

**Issue by Legendans** [ybw0014/HeadLimiter#7]
Plugins 
HeadLimiter-Build 8 (git 80c0aae)
GuizhanLibPlugin-Build 35 (git 11baf1f)

server
paper 1.18.2

No error log

Restarting the server after changing the default config.yml shows no change
items-amount: 15
The limit is still the default

    items.
      - CARGO_NODE_INPUT
      - CARGO_NODE_OUTPUT
      - CARGO_NODE_OUTPUT_ADVANCED
      - CARGO_NODE
      - CARGO_MANAGER
      - ENERGY_CONNECTOR
and other modifications are also invalid

No change after server restart

Found that changing items-amount: 15 to amount: 15
After reloading, it works

But the items: change never worked

**Comment by HiTech0926** [comment]
I have also encountered such a problem, please fix it.
我也遇到了这样的问题，请你们修复

**Comment by ybw0014** [comment]
请使用 [BlockLimiter](https://github.com/ybw0014/BlockLimiter)，懒得修了
